version: '3'
services:
  dbpostgres:
    image: postgres
    volumes:
      - ./user_db-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_db

volumes:
  user_db-data: